account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('account/create/', views.UserCreateView.as_view(), name='new_account'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(next_page='/'), name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/create', views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('drafts/', views.PostDraftListView, name='post_draft_list'),
    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='add_comment_to_post'),
    path('comment/list/<int:pk>/', views.CommentListView.as_view(), name='comment_list'),
    path('comment/detail/<int:pk>/', views.CommentDetailView.as_view(), name='comment_detail'),
    path('comment/update/<int:pk>/', views.CommentUpdateView.as_view(), name='comment_update'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('account/', include('account.urls')),
    path('', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings



class Post(models.Model):
    auther = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=False, null=False)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # publish = models.IntegerField
    publish = models.BooleanField(default=True)
    limited_publish = models.BooleanField(default=False)

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments', null=True,)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text



class Image(models.Model):
    src = models.ImageField('添付画像', upload_to='media/', blank=True)
    target = models.ForeignKey(
        Post, verbose_name='image',
        blank=True, null=True,
        on_delete=models.CASCADE
    )

blog/forms.py
from django import forms
from .models import Post, Comment, Image

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("auther", "title", "text", "publish", "limited_publish",)


class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

class ImageForm(forms.ModelForm):
    src = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )
    class Meta:
        model = Image
        fields = ("src",)
        extra=5

class CommentUpdateForm(forms.ModelForm):


    class Meta:
        model = Comment
        fields = ('approved_comment',)





# ImageFormset = forms.inlineformset_factory(
#     Possrct,Image, fields= (('__all__')),
#     extra=5,

blog/views.py
from os import sendfile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment, Image
from .forms import PostCreateForm, CommentCreateForm, ImageForm, CommentUpdateForm
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.db import transaction





class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    ordering =['-created_at']
    paginate_by = 10
    template_name = "blog/post_list.html"

    def get_queryset(self):
        queryset = Post.objects.all()
        # print('title', queryset.last().title)
        if 'query' in self.request.GET:
            qs = self.request.GET['query']
            queryset =queryset.filter(title__contains=qs)
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # data_list = Image.objects.filter(src=self.request.src, id=self.kwargs['pk'])
        context['images'] = Image.objects.all()
        return context



class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    form_class2 =ImageForm
    success_url = reverse_lazy('post_list')
    template_name = "blog/post_create.html"

    def get_context_data(self, **kwargs):
        context= CreateView.get_context_data(self, **kwargs)
        form2 = self.form_class2(self.request.GET)
        context.update({'form2':form2})
        return context


    def form_valid(self, form):
        form2 = self.form_class2(self.request.POST or None)

        if form2.is_valid():
            with transaction.atomic():
                form.save()
                form2.save()
            messages.success(self.request, "保存しました")

            return self.form_valid(form2)

        else:
            self.form_invalid(form)

        return super().form_valid(form)


    # def form_invalid(self, form):
    #     messages.warning(self.request, "保存できませんでした")
    #     return super().form_invalid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('post_list')
    template_name = "blog/post_update.html"

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)


    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした")
        return super().form_invalid(form)

    def test_func(self):
        post =self.get_object()
        if self.request.user == post.auther:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = "blog/post_delete.html"

    def test_func(self):
        post =self.get_object()
        if self.request.user == post.auther:
            return True
        return False

class PostDraftListView(ListView):
    model = Post
    context_object_name = 'drafts'
    paginate_by = 10
    template_name = "blog/post_draft.html"

    def get_queryset(self):
        return Post.objects.filter(publish=False)



class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentCreateForm
    template_name = "blog/comment_create.html"

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("post_detail",kwargs={"pk":self.kwargs["pk"]} )



class CommentListView(ListView):
    model = Comment
    context_object_name = 'comments'
    ordering =['-created_at']
    paginate_by = 10
    template_name = "blog/comment_list.html"


class CommentDetailView(DetailView):
    model = Comment
    template_name = "blog/comment_detail.html"


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentUpdateForm
    template_name = "blog/comment_update.html"

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)


    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした")
        return super().form_invalid(form)

    def test_func(self):
        post =self.get_object()
        current_user = self.request.user
        return current_user.pk == self.kwargs['pk'] or current_user.is_superuser

    def get_success_url(self):
        return reverse_lazy('comment_list', kwargs={'pk': self.object.pk})

# @login_required
# def comment_approve(request, pk):
#     comment = get_object_or_404(Comment, pk=pk)
#     comment.approve()
#     return redirect('blog/post_detail', pk=comment.post.pk)


# @login_required
# def comment_remove(request, pk):
#     comment = get_object_or_404(Comment, pk=pk)
#     comment.delete()
#     return redirect('blog/post_detail', pk=comment.post.pk)

templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>nagi'blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
    <div class="page-header">
    <form class="form_inline navbar_search" method="GET" action="{% url 'post_list'%}">{% csrf_token %}
    <input id="srchfld" class="srchtxt" type="text" name="query" />
    </form>
    {% if user.is_authenticated %}
    <a href="{% url 'post_create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
    <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'account:logout' %}">Log out</a>)</small></p>
    {% else %}
        <a href="{% url 'account:login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
    {% endif %}
        <h1><a href="/">nagi's blog</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/blog/comment_create.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>新しいコメント</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

templates/blog/comment_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if comment.created_at %}
            <div class="date">
                {{ post.created_at }}
            </div>
            {% endif %}
        <h2>{{ comment.author }}</h2>
        <p>{{ comment.text|linebreaksbr }}</p>
{% endblock %}

templates/blog/comment_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
        {% for comment in comments %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'comment_update' pk=comment.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <div class="comment">
            <p>created: {{ comment.created_at }}</p>
             <h2><a href="{% url 'comment_detail' pk=comment.pk %}">{{ comment.author }}</a></h2>
            <p>{{ comment.text|linebreaksbr }}</p>
        </div>
        {% endif %}
        {% if not user.is_authenticated %}
        {% if comment.approved_comment %}
        <a class="btn btn-default" href="{% url 'comment_update' pk=comment.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <div class="comment">
            <p>created: {{ comment.created_at }}</p>
             <h2><a href="{% url 'comment_detail' pk=comment.pk %}">{{ comment.author }}</a></h2>
            <p>{{ comment.text|linebreaksbr }}</p>
        </div>
        {% endif %}
        {% endif %}

        {% endfor %}
{% endblock %}

templates/blog/comment_update.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>コメントの認証</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">認証</button>
    </form>
{% endblock %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="PostCreateForm"　enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        {{ form2.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Delete</h2>
    <p>本当に{{ object.title }}を削除しますか？<p>
    <form method="POST" class="postCreateform">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-danger">delete</button>
    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.created_at %}
            <div class="date">
                {{ post.created_at }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'post_update' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'post_delete' pk=post.pk %}"><span class=" glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% for image  in images %}
    <div class="src">
        <img src="{{ image.src.url }}" style="width: 300px;height: auto;"/>
    </div>
{% endfor %}
    <hr>
    <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=post.pk %}">コメントを追加する</a>
    <a class="btn btn-default" href="{% url 'comment_list' pk=post.pk  %}">コメント一覧</a>
{% for comment in post.comments.all %}
    {% if user.is_authenticated %}
    <div class="comment">
        <div class="date">
            {{ comment.created_at }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>コメントはまだありません :(</p>
{% endfor %}
{% endblock %}

templates/blog/post_draft.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in drafts %}
        <div class="post">
            <p class="date">created: {{ post.created_at|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
        {% for post in posts %}
        <div class="post">
            <p>created: {{ post.created_at }}</p>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>

        </div>
        {% endfor %}
{% endblock %}

templates/blog/post_update.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="postCreateform">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}